### ISSUE TITLE
Odd on screen keyboard related crash on Android

### ISSUE THREAD

**Issue by grapefrukt** [haxenme/nme#103] opened 2013-08-19 21:13 UTC
Hello, I've been seeing a handful of these errors popping up in my Developer Console. So I figured I'd make an Issue here.

Unfortunately I don't have any idea what to do to trigger it. 
It has only happened to about .2% of my users, so it's not a huge deal. 

```
java.lang.NullPointerException
at org.haxe.nme.GameActivity.showKeyboard(GameActivity.java:526)
at org.haxe.nme.NME.onTouch(Native Method)
at org.haxe.nme.MainView$10.run(MainView.java:447)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1406)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1198)

**Comment by thomasuster** [comment] 2015-06-29 16:22
![screen shot 2015-06-29 at 9 22 01 am](https://cloud.githubusercontent.com/assets/220965/8412693/596cd7a4-1e40-11e5-9faa-a6193f199fde.png)

**Comment by thomasuster** [comment] 2015-07-09 04:18
Getting tons of these errors reports. Unable to reproduce, pushing this as potential fix.

https://github.com/thomasuster/NME/commit/6dc167976270c89ded2e7141e45a33d9006455ae

**Comment by thomasuster** [comment] 2015-08-31 15:52
Most recent stack trace

java.lang.NullPointerException
org.haxe.nme.GameActivity.showKeyboard(GameActivity.java:1097)
org.haxe.nme.NME.onTouch(Native Method)
org.haxe.nme.MainView$8.run(MainView.java:488)
android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1463)
android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by codeservice** [comment] 2015-08-31 17:33
I did changes for text input support. Potentially it could break something. Check line activity.mKeyInTextView.requestFocus(); If null pointer exception occurred here then maybe something destroying text field mKeyInTextView. You can try this for stability improvement:

if(activity.mKeyInTextView != null)
    activity.mKeyInTextView.requestFocus();
  
If this fixed problem, then need to find reason why object empty.
Of course its not a solution only will prove point that object mKeyInTextView been destroyed
somewhere.
<code>
public static void showKeyboard(boolean show)
   {
      InputMethodManager mgr = (InputMethodManager)mContext.getSystemService(Context.INPUT_METHOD_SERVICE);
      mgr.hideSoftInputFromWindow(activity.mView.getWindowToken(), 0);
      
      if (show)
      {
         activity.mKeyInTextView.requestFocus();//<-------- check this line
         mgr.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
         // On the Nexus One, SHOW_FORCED makes it impossible
         // to manually dismiss the keyboard.
         // On the Droid SHOW_IMPLICIT doesn't bring up the keyboard.
      }
   }
</code>

**Comment by thomasuster** [comment] 2015-09-07 06:33
Hey @codeservice , thanks for adding the change. I'll try this in the next Pakka Pets build, if the error goes away I'll close this issue.

https://github.com/haxenme/nme/commit/95c15dc214fc6a7d43aec2895a62ede9cd1b49e0

**Comment by thomasuster** [comment] 2015-10-16 20:27
Let's assume this fixes it. If we get reports after building with NME that includes this change we should re-open. https://github.com/haxenme/nme/commit/95c15dc214fc6a7d43aec2895a62ede9cd1b49e0

**Closed by thomasuster** 2015-10-16 20:27 UTC
Labels: bug
