### ISSUE TITLE
AudioTest not building for iOS

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#528] opened 2018-09-01 20:57 UTC
Repro Steps:

```
haxelib install nme
git clone git@github.com:haxenme/nme.git
cd nme/samples/AudioTest/
nme test ios
open bin/ios/AudioTest.xcodeproj/
Select AudioTest on left side 
Under team drop down, select your personal development team
Select a simulator to run it on
Product > Run
```

Expected: Should build to phone
Actual: Fails with build error

```
ld: library not found for -lnme
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thomasuster** [comment] 2018-09-01 21:13
Also reproducible with DispalyingABitmap sample project.

**Comment by thomasuster** [comment] 2018-09-01 22:10
Ahh forgot...

```
cd nme/project
neko build.n ios
```

That fixed it.

**Comment by thomasuster** [comment] 2018-09-01 22:27
I think `haxelib run nme remake ios` also does this step. I think this use to be a thing when you did `haxelib run nme setup ios`. 

@hughsando 
Is this the intended? If so, please reassign to me and I can add some documentation is a PR. Else, what should we do to fix this?

**Comment by hughsando** [comment] 2018-09-04 01:08
I am not 100% sure what to do here.
I dropped the ios libs builds from the distro because there was becoming too many of them.  The idea was that you can use the mechanics of hxcpp to effectively build the library in the cache for as many architectures as you like.  This also opens up the possibility of moving more of the startup files to the template system to allow easier customization.  Ios seems to be moving to just arm64, so maybe I could distribute this.
Which ever way it goes, it should work out of the box, so I see 3 possibilities.
1. Like now, but auto-build the libnme as needed.  I don't like this so much since this needs write-access to the install location. 
2. Force the static flag on.  This was how it was intended to work, so maybe just get this working better.  I might also need to add something to the hxcpp tool to prevent certain libraries from being flushed from the cache - or maybe not.
3. Add the libs  (arm64, simulator64) to the release.  This could make it faster to get started.

**Comment by thomasuster** [comment] 2018-09-08 20:05
Option 2 seems good to me at a glance. Would this just compile linking statically to sources it needs inside NME?

**Comment by thomasuster** [comment] 2018-10-27 22:31
We can probably close this if we merge https://github.com/haxenme/nme/pull/564. Not the best outcome but at least documentation would not cover this.

**Closed** 2019-02-19 05:47 UTC
Labels: feature request
